apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: zeusmarval/inventory:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBIT_URI
              value: "amqp://guest:guest@{IPAddress minikube}"
            - name: MONGODB_URI
              value: "mongodb://{IPAddress minikube}/inventory"
            - name: SERVER_PORT
              value: "8080"